version: 0.2

env:
  variables:
    NPM_CONFIG_PRODUCTION: "false"

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.12
    commands:
      - echo "Installing CDK dependencies..."
      - (cd infra && npm ci --no-progress)
      - echo "Installing Checkov..."
      - pip3 install checkov

  build:
    commands:
      - echo "Building CDK infrastructure..."
      - (cd infra && npm run build)
      - echo "Synthesizing CDK stacks..."
      - (cd infra && npx cdk synth --context withAssets=false)
      - echo "Running Checkov security scan..."
      - checkov -d infra/cdk.out --framework cloudformation || echo "⚠️ Checkov found issues, continuing (review for production)"

artifacts:
  files:
    - "infra/cdk.out/**/*"
  name: IacSynthOutput

cache:
  paths:
    - "~/.npm/**/*"
    - "~/.cache/pip/**/*"
