// ============================================================
// AUTO-GENERATED FILE — DO NOT EDIT
//
// This file is generated by the KIT dev server / build process.
// Any manual changes will be overwritten on the next build.
// ============================================================

import { ApiNamespaceClient as __KIT_ApiNamespaceClient__ } from '@aws-blocks/blocks/client';

export const api = __KIT_ApiNamespaceClient__('api');
export const authApi = __KIT_ApiNamespaceClient__('authApi');

export const generateClient = (config) => ({
    api: __KIT_ApiNamespaceClient__('api', config),
    authApi: __KIT_ApiNamespaceClient__('authApi', config),
});
