// ============================================================
// AUTO-GENERATED FILE — DO NOT EDIT
//
// This file is generated by the KIT dev server / build process.
// Any manual changes will be overwritten on the next build.
// ============================================================

// No API or auth blocks — static site only.
